Repository CleanEngine/cleanengine-be, pull requests merged in 2025-05, with the labels that each got.

#23 Feat/trade core
  src/main/java/com/cleanengine/coin/chart/dto/TradeEventDto.java
  src/main/java/com/cleanengine/coin/order/domain/BuyOrder.java
  src/main/java/com/cleanengine/coin/order/domain/SellOrder.java
  src/main/java/com/cleanengine/coin/trade/application/TradeBatchProcessor.java
  src/main/java/com/cleanengine/coin/trade/application/TradePair.java
  src/main/java/com/cleanengine/coin/trade/application/TradeQueueManager.java
  src/main/java/com/cleanengine/coin/trade/application/TradeService.java
  src/main/java/com/cleanengine/coin/trade/repository/TradeRepository.java
  src/main/java/com/cleanengine/coin/user/domain/Account.java
  src/main/java/com/cleanengine/coin/user/info/infra/AccountRepository.java
  src/main/java/com/cleanengine/coin/user/info/infra/WalletRepository.java
  src/test/java/com/cleanengine/coin/trade/application/TradeQueueManagerTest.java
Labels: Feature

#46 fix:변동률 계산 로직 수정
  src/main/java/com/cleanengine/coin/chart/service/RealTimeTradeService.java
Labels: bug

#51 config: 백엔드 배포 시 타 서비스에 영향도 없도록 변경
  .github/workflows/start-service.yml
Labels: enhancement
